#
# Ferrum makefile (modifed sbPOM makefile)
#

#-----------------------------------------------------------------------
# Settings that depend on the system and the compiler
#-----------------------------------------------------------------------
# Set macros
CPP = cpp -P
FC = mpifort
LD = mpifort
CLEAN = rm

# Set miscellaneous compiler flags
#MISCFLAGS = -g -fcheck=all -fbacktrace -fbounds-check -Wall#-ffpe-trap=underflow,denormal,zero,overflow -Wall #-Warray-temporaries -Wcharacter-truncation -Wconversion-extra  -Wrealloc-lhs
MISCFLAGS =

# Set libraries and include files
NETCDFINC = -I/usr/include/x86_64-linux-gnu -I./
NETCDFLIB = -L/usr/lib/x86_64-linux-gnu

#FFLAGS = -ip -O3 -lmpi  $(NETCDFINC)
#FFLAGS = -check bounds -check format -lmpi  $(NETCDFINC)
#FFLAGS = -check bounds  -lmpi  $(NETCDFINC)
#FFLAGS = -O3 -fp-model precise  -assume byterecl $(NETCDFINC)
#FFLAGS = -O3 -debug minimal -fp-model precise -override-limits $(NETCDFINC)
FFLAGS = -O3 $(NETCDFINC) $(MISCFLAGS)

#LIBS = -ip  -O3  -lmpi $(NETCDFLIB) -lpnetcdf
#LIBS =  -check bounds  -lmpi $(NETCDFLIB) -lpnetcdf
#LIBS = -O3 -fp-model precise -assume byterecl  $(NETCDFLIB) -lpnetcdf
# LIBS = -O3 -debug minimal -fp-model precise -override-limits $(NETCDFLIB) -lpnetcdf
LIBS = $(NETCDFLIB) -lpnetcdf
#-----------------------------------------------------------------------
# Set the executable
#-----------------------------------------------------------------------
BIN = ferrum

#-----------------------------------------------------------------------
# Define directories
#-----------------------------------------------------------------------
SRCDIR = pom
OBJDIR = obj
OUTDIR = out

#-----------------------------------------------------------------------
# Define objects
#-----------------------------------------------------------------------
 OBJS = module_time.o    \
        globals.o        \
        config.o         \
        clim.o           \
        bry.o            \
        seaice.o         \
        air.o            \
        io.o             \
        tide.o           \
        parallel_mpi.o   \
        io_pnetcdf.o     \
        river.o          \
        advance.o        \
        solver.o         \
        initialize.o     \
        heat.o           \
        interp.o         \
        wind.o           \
        tsforce.o        \
        assim.o          \
        assim_drf.o      \
        mcsst.o          \
        uvforce.o        \
        pom.o
VPATH = $(SRCDIR)

#-----------------------------------------------------------------------
# Set implicit rules for compilation
#-----------------------------------------------------------------------
%.o: %.f90
	@echo
	$(FC) -c $(FFLAGS) -ffree-form $<

%.o: %.f
	@echo
	$(FC) -c $(FFLAGS) $<

#-----------------------------------------------------------------------
# Set implicit rules for dependencies
#-----------------------------------------------------------------------
%.f: %.F
	@echo
	$(CPP) $(FFLAGS) $< > $*.f

#-----------------------------------------------------------------------
# Create the executable
#-----------------------------------------------------------------------
$(BIN): $(OBJS)
	@mkdir -p $(OUTDIR)
	@echo
	$(LD) $(FFLAGS) -o $(BIN) $(OBJS) $(LIBS)

#-----------------------------------------------------------------------
# Cleaning target
#-----------------------------------------------------------------------
clean:
	@rm -f *.o *.mod *.il $(BIN)
